language: elixir
elixir:
  - 1.6.6
  - 1.7.2
  - 1.8.2
  - 1.9.0

otp_release:
  - 20.3
  - 22.0

matrix:
  exclude:
  - elixir: 1.6.6
    otp_release: 22

script:
  - mix format --check-formatted
  - mix deps.get

  # check for any trailing whitespace
  - "! git grep ' $' -- \\*.exs"

sudo: false

cache:
  directories:
    - _build
    - deps
